### ISSUE TITLE
Solis Control Stopped after 1.6.2 Update

### ISSUE THREAD

**Issue by rustyscrew7** [custom-components/pyscript#710]
Any Ideas what could cause this after pyscript update to 1.6.2 ?

Source: custom_components/pyscript/eval.py:511

Exception in <file.solis_control.solis_control> line 98: inverterList = response.json() ^ AttributeError: '_BaseRequestContextManager' object has no attribute 'json'

Thanks

**Comment by eddysteurs** [comment]
i have the same problem , roll back to 1.6.1 of pyscript and all is good again (tried upgrade twice, same error)
This error originated from a custom integration.

Logger: custom_components.pyscript.file.solis_control.solis_control
Source: custom_components/pyscript/eval.py:511
integration: Pyscript Python scripting (documentation, issues)
First occurred: 12:16:58 (5 occurrences)
Last logged: 12:24:13

Exception in <file.solis_control.solis_control> line 117: inverterList = response.json() ^ AttributeError: '_BaseRequestContextManager' object has no attribute 'json'

**Comment by craigbarratt** [comment]
I'm not familiar with the solis_control.py code.  It looks like there is an issue for this [here](https://github.com/stevegal/solis_control/issues/34).

I'd recommend try removing the await on the previous line 116.

**Comment by abandyb** [comment]
@craigbarratt is there any hotfix for pyscript planned?  I've only done a bit of meddling with installed custom components so my preference is to wait for pyscript to be fixed. 

Referring to the [https://github.com/stevegal/solis_control/issues/34](solis control) issue referenced, there are actually 4 methods with an await - Should they all be non-awaited? 

One final question regarding HA updates - because I reverted back to 1.6.1, I now have a pyscript 1.6.2 update which I continue to ignore until it is fixed - is it true that as long as I never click on that to update it, it will sit there indefinitely, or will it somehow get picked up by other HA updates?

thanks!

**Comment by IgnusG** [comment]
> One final question regarding HA updates - because I reverted back to 1.6.1, I now have a pyscript 1.6.2 update which I continue to ignore until it is fixed - is it true that as long as I never click on that to update it, it will sit there indefinitely, or will it somehow get picked up by other HA updates?
> 
> thanks!

You can press skip (next to the update button) to remove the notification. It will not auto update unless you have any automations or integrations setup that would do so for you.

**Comment by craigbarratt** [comment]
I pushed a potential fix; please try the latest (master).

**Comment by jparnellx** [comment]
> I pushed a potential fix; please try the latest (master).

Hi, I just downloaded the latest version but still get the same error as the original poster.

**Comment by craigbarratt** [comment]
To be sure, did you download 1.6.2 or the current github master?

Can you check whether the variable `do_await` appears anywhere in `config/custom_components/pyscript/eval.py`?

**Comment by jparnellx** [comment]
> To be sure, did you download 1.6.2 or the current github master?
> 
> Can you check whether the variable `do_await` appears anywhere in `config/custom_components/pyscript/eval.py`?

Apologies, my bad. HA hadn't been restarted after i updated.
I can confirm the issue is now FIXED!!
Thank you very much.

**Comment by craigbarratt** [comment]
Released 1.6.3 with this fix.
