### ISSUE TITLE
pyscript is not defined when using state.persist in new app

### ISSUE THREAD

**Issue by Nxt3** [custom-components/pyscript#86]
I was attempting to use the `state.persist` functionality for dynamic variables in the app like so below. Along with `pyscript` being `not defined`, I have other variables that keep showing up `not defined`. It's my understanding that I shouldn't have to declare the variables as `global` if I'm not writing to them but I am probably wrong.

```python
from load_app import loadApp

registered_triggers = []

@time_trigger('startup')
def personTrackerStartup():
    loadApp('person_tracker', buildPersonTracker)


def buildPersonTracker(config):
    global registered_triggers
    personID = config.get('person')
    personName = personID.split('.')[1]
    inputID = f'input_select.{personName}'
    state.persist(f'pyscript.{personName}_person_tracker') # persist

    @task_unique(f'{personName}_tracker')
    @state_trigger(f'{personID} != {personID}.old')
    def tracker(value=None):
        global personID
        personState = state.get(inputID)

        if value == 'home':
            if personState != 'Just Left':
                input_select.select_option(
                    entity_id=inputID, option='Just Arrived')

                minutes = 10
                waitForChanges = task.wait_until(
                    timeout=minutes * 60,
                    state_trigger=(f'{personID} != "home"'),
                    state_check_now=False
                )

                if waitForChanges['trigger_type'] == 'timeout':
                    # 10 mins elapsed without leaving home
                    input_select.select_option(
                        entity_id=inputID, option='Home')
                else:
                    return
        else:
            if personState not in ['Just Left', 'Away', 'Extended Away']:
                input_select.select_option(
                    entity_id=inputID, option='Just Left')

                minutes = 20
                waitForChanges = task.wait_until(
                    timeout=minutes*60,
                    state_trigger=(f'{personID} == "home"'), # personID not defined
                    state_check_now=False
                )

                if waitForChanges['trigger_type'] == 'timeout':
                    # 20 mins elapsed without coming home
                    input_select.select_option(
                        entity_id=inputID, option='Away')
                else:
                    hours = 2
                    waitForChanges = task.wait_until(
                        timeout=hours*3600,
                        state_trigger=(f'{personID} == "home"'), # personID not defined
                        state_check_now=True
                    )

                    if waitForChanges['trigger_type'] == 'timeout':
                        # 2hrs elapsed without coming home
                        input_select.select_option(
                            entity_id=inputID, option='Extended Away')
                    else:
                        return

    @state_trigger(f'input_select.{personName} != input_select.{personName}.old')
    def watchPersonInputChanges(value=None):
        # persist person tracker input across reboots
        pyscript[f'{personName}_person_tracker'] = value # pyscript is not defined

    # register to global scope
    registered_triggers.append([tracker, watchPersonInputChanges])
```

```
2020-11-06 16:04:11 ERROR (MainThread) [custom_components.pyscript.apps.person_tracker.tracker] Exception in <apps.person_tracker.tracker> line 36:
state_trigger=(f'{personID} != "home"'),
^
NameError: global name 'personID' is not defined
2020-11-06 16:04:11 ERROR (MainThread) [custom_components.pyscript.apps.person_tracker.watchPersonInputChanges] Exception in <apps.person_tracker.watchPersonInputChanges> line 80:
pyscript[f'{personName}_person_tracker'] = value
^
NameError: name 'pyscript' is not defined
2020-11-06 16:04:14 ERROR (MainThread) [custom_components.pyscript.apps.person_tracker.tracker] Exception in <apps.person_tracker.tracker> line 54:
state_trigger=(f'{personID} == "home"'),
^
NameError: global name 'personID' is not defined
2020-11-06 16:04:14 ERROR (MainThread) [custom_components.pyscript.apps.person_tracker.watchPersonInputChanges] Exception in <apps.person_tracker.watchPersonInputChanges> line 80:
pyscript[f'{personName}_person_tracker'] = value
^
NameError: name 'pyscript' is not defined
```

**Comment by dlashua** [comment]
This appears to be the right way to use `state.persist`. 

However, it's the wrong way to use `global`. That's why you're getting "global name 'personID' is not defined.


Also, this syntax...
```
pyscript[f'{personName}_person_tracker'] = value
```
... is incorrect. 

Instead you should use...
```
state.set(f'pyscript.{personName}_person_tracker', value)
```

You're trying to use `pyscript` like a `dict()`, and it is not. You can't do this with `binary_sensor` or any other Home Assistant domain either.

You can do...
```
pyscript.whatever = whatever
```
But, once you have a variable that is holding your entity_id, you need the `state.set` syntax instead.


I'd need to see the input (the values for "config") to be any more helpful.

**Comment by Nxt3** [comment]
Ah yeah I didn't realize `pyscript` wasn't a dict and that you needed to use `state.set`; must have missed that in the docs.

Well this is what my config looks like:

```yaml
apps:
  person_tracker:
    - person: person.tony_stark
```

and when I put logs in the app like so:

```python
def buildPersonTracker(config):
    global registered_triggers
    log.debug(config) # prints: {'person': 'person.tony_stark'}
    personID = config['person']
    log.debug(f'personID: {personID}') # prints: 'person.tony_stark'
    personName = personID.split('.')[1]
    inputID = f'input_select.{personName}'
    state.persist(f'pyscript.{personName}_person_tracker')
    ...
```

and I still get `personID is not defined`.

**Comment by dlashua** [comment]
in `def tracker` you don't need `global personID`. That should resolve that issue, I think.

**Comment by Nxt3** [comment]
That doesn't seem to fix the problem. Here's my updated code:

```python
from load_app import loadApp

registered_triggers = []

@time_trigger('startup')
def personTrackerStartup():
    loadApp('person_tracker', buildPersonTracker)

def buildPersonTracker(config):
    global registered_triggers
    log.debug(config) # prints: {'person': 'person.tony_stark'}
    personID = config['person']
    log.debug(f'personID: {personID}') # prints: 'personID: person.tony_stark'
    personName = personID.split('.')[1]
    log.debug(f'personName: {personName}') # prints: 'personName: tony_stark'
    inputID = f'input_select.{personName}'
    state.persist(f'pyscript.{personName}_person_tracker')

    @task_unique(f'{personName}_tracker')
    @state_trigger(f'{personID} != {personID}.old')
    def tracker(value=None):
        personState = state.get(inputID)

        if value == 'home':
            if personState != 'Just Left':
                input_select.select_option(
                    entity_id=inputID, option='Just Arrived')

                minutes = 10
                waitForChanges = task.wait_until(
                    timeout=minutes*60,
                    state_trigger=(f'{personID} != "home"'),
                    state_check_now=False
                )

                if waitForChanges['trigger_type'] == 'timeout':
                    # 10 mins elapsed without leaving home
                    input_select.select_option(
                        entity_id=inputID, option='Home')
                else:
                    return
        else:
            if personState not in ['Just Left', 'Away', 'Extended Away']:
                input_select.select_option(
                    entity_id=inputID, option='Just Left')

                minutes = 20
                waitForChanges = task.wait_until(
                    timeout=minutes*60,
                    state_trigger=(f'{personID} == "home"'), # personID not defined
                    state_check_now=False
                )

                if waitForChanges['trigger_type'] == 'timeout':
                    # 20 mins elapsed without coming home
                    input_select.select_option(
                        entity_id=inputID, option='Away')
                else:
                    hours = 2
                    waitForChanges = task.wait_until(
                        timeout=hours*3600,
                        state_trigger=(f'{personID} == "home"'), # personID not defined
                        state_check_now=True
                    )

                    if waitForChanges['trigger_type'] == 'timeout':
                        # 2hrs elapsed without coming home
                        input_select.select_option(
                            entity_id=inputID, option='Extended Away')
                    else:
                        return

    @state_trigger(f'input_select.{personName} != input_select.{personName}.old')
    def watchPersonInputChanges(value=None):
        # persist person tracker input across reboots
        state.set(f'pyscript.{personName}_person_tracker', value)

    # register to global scope
    registered_triggers.append([tracker, watchPersonInputChanges])
```

**Comment by dlashua** [comment]
Ahhh... I missed one bit.

At the top of `def tracker()` you'll need to declare `personID` as nonlocal. Like this:

```
    def tracker(value=None):
      nonlocal personID
```

`nonlocal` is related to `global` in that it sets the scope for a variable. 

https://www.w3schools.com/python/ref_keyword_nonlocal.asp

**Comment by Nxt3** [comment]
That seems to have fixed things up. Had no idea that was a thing. Thanks for the help :)
